#!/usr/bin/env python3
"""Leak check: does the shipped bundle hand the solver anything the author did not mean to ship?

    python3 .claude/skills/leak-check/leak.py task100 [--asof 2027-05-14] [--quiet]

Reads prompt.md, submission.md, DESIGN_NOTE.md (if present) and target/ (unzipping target.zip into
the scratch dir when target/ is absent), and writes <task>/leak_check_report.md. Exit status is 2 on
LEAK, 1 on REVIEW, 0 on CLEAN. Spawns nothing. The solver's-eye read that only a reader can do is
the second half of the /leak-check command and is appended to the same report.

Eleven sweeps, each a function below, each tagged LEAK (ship-stopping), REVIEW (a reader decides) or
INFO. The design of every sweep is the same: the thing it hunts is something the author knows and the
solver must not be told, so the sweep takes the author's own text (the submission's answers, the
design note's stump vocabulary, the generator's library names) and looks for it in the solver's text.
"""
import argparse
import io
import json
import os
import re
import subprocess
import sys
import tempfile
import zipfile
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SCRUB = REPO / ".claude/skills/reduce-house-fixes/scripts/scrub_producer_metadata.py"

DOC_EXT = {".md", ".txt", ".docx", ".pdf", ".rtf", ".html", ".htm"}
DATA_EXT = {".csv", ".tsv", ".json", ".xlsx", ".xls", ".parquet", ".jsonl", ".xml", ".yaml", ".yml"}
IMG_EXT = {".png", ".jpg", ".jpeg", ".svg"}

# File names an author writes and a solver reads as a map.
BAD_NAME = re.compile(
    r"(trap|decoy|distractor|naive|rung|stump|ladder|golden|answer|truth|hidden|secret|solution|answer_key|"
    r"clean(ed)?_|_fixed|correct(ed)?_|quality_note|known_issue|reconcil\w*_needed|synthetic|generated|"
    r"_seed|placeholder|dummy|sample_|test_|_v\d+\b|\bcopy\b|final_final|backup|\.bak$|~$)",
    re.I,
)

# Vocabulary that belongs to the author or the toolchain, never to the organisation in the fiction.
AUTHOR_VOCAB = [
    (r"\btraps?\b", "LEAK"), (r"\bdecoys?\b", "LEAK"), (r"\bna[iï]ve\b", "REVIEW"), (r"\brungs?\b", "LEAK"),
    (r"\bstump(s|ed|ing)?\b", "LEAK"), (r"\bladder\b", "REVIEW"), (r"\bgolden\b", "LEAK"),
    (r"\banswer key\b", "LEAK"), (r"\bcorrect basis\b", "LEAK"), (r"\bthe solver\b", "LEAK"),
    (r"\bthe model\b", "REVIEW"), (r"\brubric\b", "LEAK"), (r"\bdeterminis\w+", "LEAK"),
    (r"\bsynthetic\b", "REVIEW"), (r"\bgenerated by\b", "REVIEW"), (r"\bplaceholder\b", "LEAK"),
    (r"\blorem\b", "LEAK"), (r"\bTODO\b", "LEAK"), (r"\bFIXME\b", "LEAK"), (r"\bXXX\b", "LEAK"),
    (r"\bas an ai\b", "LEAK"), (r"python-docx|openpyxl|reportlab|matplotlib|pandas|numpy|faker|pyarrow", "LEAK"),
    (r"\brandom seed\b|\bseed\s*=\s*\d+", "LEAK"), (r"\bscratchpad\b|/Users/|/home/|C:\\\\Users", "LEAK"),
    (r"\bclaude\b|\banthropic\b|\bchatgpt\b|\bopenai\b|\bllm\b", "LEAK"),
    (r"\bdesign note\b|\bgenerator\b", "REVIEW"), (r"\bdistractor\b", "LEAK"),
    (r"\u2014", "REVIEW"),  # em dash: the house tell
]

# Sentences that announce the decisive step.
ANNOUNCE = [
    r"\b(make sure|be sure|remember|don'?t forget|do not forget|be careful|take care|watch out|bear in mind|keep in mind)\b",
    r"\b(note that|note:|nb[:.]|n\.b\.|important[:!])",
    r"\b(must|should|need(s)? to|have to|has to)\b[^.]{0,80}\b(join|exclude|exclud\w+|include|match|reconcil\w+|link|map|merge|dedup\w*|group|deduplicat\w+|carry forward|restate|re-?key|convert|adjust|rebas\w+|re-?weight\w*)\b",
    r"\b(the right|the correct|the proper|the true|the real)\s+(basis|unit|population|grain|definition|denominator|method|reading|figure|count)\b",
    r"\b(instead of|rather than|not simply|not just|not merely)\b[^.]{0,60}\b(count|sum|rows?|lines?|records?|total)\b",
]

STOP = set("""a an and are as at be been being but by can could did do does doing for from had has have
having he her here hers him his how i if in into is it its itself just me more most my no nor not of
off on once only or other our out over own same she should so some such than that the their them then
there these they this those through to too under until up very was we were what when where which while
who whom why will with would you your one two three each every any all both either neither whole new
old also per via onto upon within without across against between among because before after above
below during whether rather instead yet still even ever never much many few less least made make
makes making gets get got set sets which about their there these those where would could should
figure figures number numbers value values answer answers column columns file files table tables""".split())

NUM = re.compile(r"(?<![\w.])[-+]?\d{1,3}(?:,\d{3})+(?:\.\d+)?|(?<![\w.,])[-+]?\d+\.\d+|(?<![\w.,])\d{3,}(?![\w.,])")


# ------------------------------------------------------------------ text extraction

def xml_text(data):
    return re.sub(r"<[^>]+>", " ", data.decode("utf-8", "ignore"))


def read_docx(path):
    out, extras = [], {}
    with zipfile.ZipFile(path) as z:
        names = z.namelist()
        for n in names:
            if n.startswith("word/") and n.endswith(".xml"):
                raw = z.read(n)
                out.append(xml_text(raw))
                if n == "word/document.xml":
                    if b"<w:del " in raw or b"<w:ins " in raw:
                        extras["tracked_changes"] = True
                    if b"<w:vanish" in raw:
                        extras["hidden_text"] = True
                if n == "word/comments.xml":
                    extras["comments"] = len(re.findall(rb"<w:comment ", raw))
            if n.startswith("docProps/"):
                extras.setdefault("docprops", []).append(xml_text(z.read(n)))
        media = [n for n in names if n.startswith("word/embeddings/") or n.startswith("word/media/")]
        if media:
            extras["embedded"] = media
    return "\n".join(out), extras


def read_xlsx(path):
    extras, out = {}, []
    try:
        import openpyxl
        wb = openpyxl.load_workbook(path, data_only=True, read_only=False)
    except Exception as e:
        return "", {"error": str(e)}
    hidden_sheets = [ws.title for ws in wb.worksheets if ws.sheet_state != "visible"]
    if hidden_sheets:
        extras["hidden_sheets"] = hidden_sheets
    try:
        dn = list(wb.defined_names.keys()) if hasattr(wb.defined_names, "keys") else [d.name for d in wb.defined_names.definedName]
        if dn:
            extras["defined_names"] = dn
    except Exception:
        pass
    for ws in wb.worksheets:
        hc = [k for k, d in ws.column_dimensions.items() if d.hidden]
        hr = [k for k, d in ws.row_dimensions.items() if d.hidden]
        if hc or hr:
            extras.setdefault("hidden_rows_cols", {})[ws.title] = {"cols": hc[:10], "rows": hr[:10]}
        comments = 0
        for row in ws.iter_rows():
            vals = []
            for c in row:
                if c.comment:
                    comments += 1
                if c.value is not None:
                    vals.append(str(c.value))
            if vals:
                out.append("\t".join(vals))
        if comments:
            extras.setdefault("comments", {})[ws.title] = comments
    with zipfile.ZipFile(path) as z:
        extras["docprops"] = [xml_text(z.read(n)) for n in z.namelist() if n.startswith("docProps/")]
    return "\n".join(out), extras


def read_pdf(path):
    extras, out = {}, []
    try:
        import pypdf
        r = pypdf.PdfReader(str(path))
        md = r.metadata or {}
        extras["metadata"] = {k: str(v) for k, v in md.items()}
        ann = 0
        for p in r.pages:
            out.append(p.extract_text() or "")
            if "/Annots" in p:
                ann += len(p["/Annots"])
        if ann:
            extras["annotations"] = ann
        if "/EmbeddedFiles" in str(r.trailer.get("/Root", {}).keys()):
            extras["embedded_files"] = True
    except Exception as e:
        extras["error"] = str(e)
    return "\n".join(out), extras


def read_parquet(path):
    try:
        import pandas as pd
        df = pd.read_parquet(path)
        return df.to_csv(index=False), {"columns": list(df.columns)}
    except Exception as e:
        return "", {"error": str(e)}


def read_png_text(path):
    raw = path.read_bytes()
    chunks = re.findall(rb"(tEXt|iTXt|zTXt)(.{0,200})", raw, re.S)
    return " ".join(c[1].decode("latin-1", "ignore") for c in chunks), {}


def extract(path):
    ext = path.suffix.lower()
    try:
        if ext == ".docx":
            return read_docx(path)
        if ext in (".xlsx", ".xlsm"):
            return read_xlsx(path)
        if ext == ".pdf":
            return read_pdf(path)
        if ext == ".parquet":
            return read_parquet(path)
        if ext in (".png", ".jpg", ".jpeg"):
            return read_png_text(path)
        if ext in (".zip",):
            return "", {"nested_zip": True}
        return path.read_text(encoding="utf-8", errors="ignore"), {}
    except Exception as e:
        return "", {"error": str(e)}


def columns_of(path, text):
    ext = path.suffix.lower()
    if ext in (".csv", ".tsv"):
        first = text.split("\n", 1)[0]
        return [c.strip().strip('"') for c in re.split(r"[,\t;|]", first)]
    if ext in (".xlsx",):
        return [c for line in text.split("\n")[:3] for c in line.split("\t")]
    if ext == ".json":
        return re.findall(r'"([A-Za-z_][A-Za-z0-9_ ]{1,40})"\s*:', text[:20000])
    return []


# ------------------------------------------------------------------ the author's text

def submission_answers(sub):
    """Numbers and names from block 1 and block 4 of a five-block submission.md."""
    b1 = re.search(r"## 1\..*?(?=\n## 2\.)", sub, re.S)
    b4 = re.search(r"## 4\..*", sub, re.S)
    b1 = b1.group(0) if b1 else ""
    b4 = b4.group(0) if b4 else ""
    nums = set()
    for blk in (b1, b4):
        for n in NUM.findall(blk):
            s = n.replace(",", "").lstrip("+")
            try:
                v = float(s)
            except ValueError:
                continue
            if 1900 <= v <= 2100 and "." not in s:  # a year
                continue
            if abs(v) < 10 and "." not in s:
                continue
            nums.add(n.lstrip("+"))
    call = re.search(r"\*\*(.+?)\*\*", b1)
    call = call.group(1) if call else ""
    names = set()
    for blk in (b1, b4):
        for m in re.finditer(r"\b([A-Z][a-z]+(?:[ '][A-Z][a-zA-Z']+){1,4})\b", blk):
            if m.group(1).split()[0] not in ("The", "Not", "We", "Each", "Per", "For", "Deliverable", "Final", "Critical", "Step"):
                names.add(m.group(1))
    return nums, names, call, b4


def design_vocab(note, prompt_text):
    """Distinctive terms from the design note's stump and driver paragraphs that the prompt does not use."""
    if not note:
        return []
    paras = []
    for p in re.split(r"\n\s*\n", note):
        if re.search(r"\b(stump|driver|decisive|rung 0|the wrong committed|lands them)\b", p, re.I):
            paras.append(p)
    text = "\n".join(paras[:12])
    words = [w for w in re.findall(r"[a-z][a-z\-]{5,}", text.lower()) if w not in STOP]
    pw = set(re.findall(r"[a-z][a-z\-]{5,}", prompt_text.lower()))
    cnt = Counter(w for w in words if w not in pw)
    return [w for w, c in cnt.most_common(40) if c >= 2 and not w.startswith(("solver", "respons", "portal", "rubric"))][:25]


# ------------------------------------------------------------------ sweeps

class Report:
    def __init__(self):
        self.items = defaultdict(list)  # sweep -> [(level, file, detail)]

    def add(self, sweep, level, file, detail):
        self.items[sweep].append((level, str(file), detail))

    def level(self):
        levels = [lv for v in self.items.values() for lv, _, _ in v]
        if "LEAK" in levels:
            return "LEAK"
        if "REVIEW" in levels:
            return "REVIEW"
        return "CLEAN"


def ctx(text, m, w=70):
    a, b = max(0, m.start() - w), min(len(text), m.end() + w)
    return re.sub(r"\s+", " ", text[a:b]).strip()


def sweep_names(files, rep):
    for f in files:
        rel = f["rel"]
        if BAD_NAME.search(rel.name) or BAD_NAME.search(str(rel.parent)):
            rep.add("1 file names", "LEAK", rel, "name matches the author's vocabulary: %s" % BAD_NAME.search(rel.name or str(rel)).group(0))
        if rel.name.startswith(".") or rel.name in ("Thumbs.db", "desktop.ini") or "__MACOSX" in str(rel):
            rep.add("1 file names", "LEAK", rel, "stray system or dot file")
        if f["ext"] in (".py", ".ipynb", ".r", ".sql", ".sh"):
            rep.add("1 file names", "REVIEW", rel, "code shipped in the input pack, confirm it is in-fiction and carries no construction of the answer")


TOOLCHAIN = re.compile(r"python-docx|openpyxl|reportlab|matplotlib|pandas|numpy|faker|pyarrow|seed\s*=|scratchpad|/Users/|claude|anthropic|lorem|placeholder|TODO|FIXME|as an ai", re.I)


def sweep_vocab(files, rep):
    for f in files:
        t = f["text"]
        if not t:
            continue
        isdata = f["ext"] in DATA_EXT
        for pat, lv in AUTHOR_VOCAB:
            # A data file carries real-world strings (GOLDEN is an Irish electoral division), so only
            # the toolchain patterns are swept there; the author's nouns are swept in documents.
            if isdata and not TOOLCHAIN.search(pat.replace("\\b", "")):
                continue
            ms = list(re.finditer(pat, t, re.I))
            if not ms:
                continue
            if pat == "\u2014":
                rep.add("2 author vocabulary", "REVIEW", f["rel"], "%d em dash(es)" % len(ms))
                continue
            rep.add("2 author vocabulary", lv, f["rel"], "%s x%d: ...%s..." % (pat, len(ms), ctx(t, ms[0])))


def sweep_answers(files, rep, nums, names, call, prompt_text):
    given = set(n for n in NUM.findall(prompt_text))
    for f in files:
        t = f["text"]
        if not t:
            continue
        isdoc = f["ext"] in DOC_EXT
        hits = []
        for n in sorted(nums, key=len, reverse=True):
            if n in given:
                continue
            digits = len(re.sub(r"\D", "", n))
            if not isdoc and digits < 5:
                continue  # a short figure recurs in any data file by chance
            m = re.search(r"(?<![\d.])" + re.escape(n) + r"(?![\d])", t)
            if m:
                hits.append((n, ctx(t, m, 50), digits))
        if hits:
            for n, c, digits in hits[:12]:
                lv = "LEAK" if (isdoc and digits >= 4) else "REVIEW"
                rep.add("3 answer figures in the pack", lv, f["rel"], "golden figure %s appears: ...%s..." % (n, c))
            if len(hits) > 12:
                rep.add("3 answer figures in the pack", lv, f["rel"], "and %d more golden figures" % (len(hits) - 12))
        if isdoc:
            for nm in names:
                for m in re.finditer(re.escape(nm), t):
                    window = t[max(0, m.start() - 120): m.end() + 120].lower()
                    if re.search(r"\b(recommend|select|winner|wins|best|top|highest|lowest|rank|first out|chosen|pick|prefer|should get|should take|goes to)\b", window):
                        rep.add("3 answer figures in the pack", "REVIEW", f["rel"], "candidate %r sits beside decision vocabulary: ...%s..." % (nm, ctx(t, m, 90)))
                        break
    if call:
        toks = [w for w in re.findall(r"[A-Za-z][A-Za-z']{3,}", call) if w.lower() not in STOP]
        for f in files:
            if f["ext"] in DOC_EXT and f["text"] and len(toks) >= 3:
                have = sum(1 for w in toks if re.search(r"\b" + re.escape(w) + r"\b", f["text"], re.I))
                if have >= max(3, int(0.7 * len(toks))):
                    rep.add("3 answer figures in the pack", "REVIEW", f["rel"], "carries %d of %d distinctive words of the committed call: %r" % (have, len(toks), call[:120]))


def sweep_design_vocab(files, rep, vocab, prompt_text):
    if not vocab:
        rep.add("4 design-note vocabulary", "INFO", "-", "no design note or no stump paragraph found, sweep skipped")
        return
    for f in files:
        if f["ext"] not in DOC_EXT or not f["text"]:
            continue
        found = []
        for w in vocab:
            m = re.search(r"\b" + re.escape(w) + r"\w*", f["text"], re.I)
            if m:
                found.append((w, ctx(f["text"], m, 45)))
        if len(found) >= 3:
            rep.add("4 design-note vocabulary", "REVIEW", f["rel"], "%d of %d stump-paragraph terms appear (%s); read whether the document names the move" % (len(found), len(vocab), ", ".join(w for w, _ in found[:6])))
    ps = [s for s in re.split(r"(?<=[.!?])\s+", prompt_text) if sum(1 for w in vocab if re.search(r"\b" + re.escape(w), s, re.I)) >= 2]
    for s in ps[:6]:
        rep.add("4 design-note vocabulary", "REVIEW", "prompt.md", "prompt sentence carries two or more stump terms: %r" % re.sub(r"\s+", " ", s)[:220])


def sweep_announce(files, rep, prompt_text):
    srcs = [("prompt.md", prompt_text)] + [(str(f["rel"]), f["text"]) for f in files if f["ext"] in DOC_EXT and f["text"]]
    for name, t in srcs:
        for s in re.split(r"(?<=[.!?])\s+", t):
            if len(s) > 400:
                continue
            for pat in ANNOUNCE:
                if re.search(pat, s, re.I):
                    rep.add("5 announcements", "REVIEW", name, re.sub(r"\s+", " ", s).strip()[:260])
                    break


def sweep_rank_artifact(files, rep, names):
    cands = [n for n in names if len(n) > 5]
    if len(cands) < 3:
        return
    for f in files:
        t = f["text"]
        if not t:
            continue
        have = [n for n in cands if n in t]
        if len(have) >= min(3, len(cands)):
            numeric = len(NUM.findall(t[:200000])) > 20
            lv = "REVIEW" if numeric else "INFO"
            rep.add("6 ranking artifacts", lv, f["rel"], "names %d of %d answer-set candidates%s; confirm it does not rank them on the decision question" % (len(have), len(cands), " beside numbers" if numeric else ""))


def sweep_hidden(files, rep):
    for f in files:
        x = f["extras"]
        for k in ("hidden_sheets", "hidden_rows_cols", "defined_names", "comments", "tracked_changes", "hidden_text", "annotations", "embedded", "embedded_files", "nested_zip"):
            if x.get(k):
                lv = "LEAK" if k in ("hidden_sheets", "hidden_text", "tracked_changes", "comments") else "REVIEW"
                rep.add("7 hidden content", lv, f["rel"], "%s: %s" % (k, json.dumps(x[k])[:200]))
        if x.get("error"):
            rep.add("7 hidden content", "REVIEW", f["rel"], "could not be read: %s" % x["error"][:120])


def sweep_columns(files, rep):
    pat = re.compile(r"(^|_)(true|truth|actual|hidden|trap|flag|is_|seed|synthetic|gen_|generated|golden|answer|correct|naive|rung|device|hazard|planted|debug|tmp|temp|internal)(_|$)", re.I)
    for f in files:
        cols = columns_of(f["rel"], f["text"]) if f["ext"] in DATA_EXT else []
        bad = [c for c in cols if c and pat.search(c)]
        if bad:
            rep.add("8 column names", "REVIEW", f["rel"], "columns a generator names and an organisation does not: %s" % ", ".join(bad[:8]))
        if f["ext"] in (".csv", ".tsv") and f["text"]:
            head = f["text"].split("\n")[:50]
            if any(re.search(r"\b(nan|NaN|None|NULL|True|False)\b", l) for l in head):
                rep.add("8 column names", "REVIEW", f["rel"], "Python-style nulls or booleans (nan/None/True/False) in the first rows")


def sweep_dates(files, rep, asof, prompt_text):
    if not asof:
        rep.add("9 dates after the setting", "INFO", "-", "no --asof given, sweep skipped (pass the fiction's as-of date)")
        return
    given = set(re.findall(r"\b(20\d\d)-(\d\d)-(\d\d)\b", prompt_text))
    for f in files:
        if not f["text"]:
            continue
        late = Counter()
        for m in re.finditer(r"\b(20\d\d)-(\d\d)-(\d\d)\b", f["text"]):
            d = "-".join(m.groups())
            if d > asof and m.groups() not in given:
                late[d] += 1
        if late:
            rep.add("9 dates after the setting", "REVIEW", f["rel"], "%d ISO dates after %s, e.g. %s" % (sum(late.values()), asof, ", ".join(sorted(late)[:5])))


def sweep_metadata(target, rep):
    if not SCRUB.exists():
        rep.add("10 container metadata", "INFO", "-", "scrub script not found")
        return
    r = subprocess.run([sys.executable, str(SCRUB), str(target)], capture_output=True, text=True)
    out = (r.stdout + r.stderr).strip()
    flagged = [l for l in out.split("\n")
               if re.search(r"python-docx|openpyxl|reportlab|matplotlib|pypdf|LibreOffice|Microsoft|outside the band|out-of-band timestamp", l, re.I)
               and not re.search(r"\bno (producer|writer|out-of-band)|clean\b", l, re.I)]
    if flagged:
        for l in flagged[:15]:
            rep.add("10 container metadata", "LEAK", "-", l.strip()[:200])
    else:
        rep.add("10 container metadata", "INFO", "-", "audit reported no writer signature (%d lines)" % len(out.split("\n")))


def sweep_prompt(prompt_text, rep):
    for pat, what in (
        (r"\[[^\]]{3,}\]", "bracketed block"),
        (r"\(\s*(CSV|XLSX|PDF|DOCX|PNG|PPTX|JSON|Parquet)\s*\)", "file.ext (Family) header"),
        (r"^\s*[-*]\s", "bulleted ask"),
        (r"\u2014", "em dash"),
    ):
        ms = list(re.finditer(pat, prompt_text, re.M))
        if ms:
            rep.add("11 prompt form", "REVIEW", "prompt.md", "%s x%d: %r" % (what, len(ms), ctx(prompt_text, ms[0], 40)))
    for pat in (r"\b(step \d|first,? (compute|calculate|join)|then (compute|calculate|join)|use the following method|the method is)\b",):
        for m in re.finditer(pat, prompt_text, re.I):
            rep.add("11 prompt form", "REVIEW", "prompt.md", "prompt enumerates method: ...%s..." % ctx(prompt_text, m, 60))


# ------------------------------------------------------------------ main

def load_target(task):
    tdir = task / "target"
    if tdir.is_dir():
        return tdir, None
    z = task / "target.zip"
    if not z.exists():
        sys.exit("no target/ and no target.zip in %s" % task)
    tmp = Path(tempfile.mkdtemp(prefix="leak-"))
    with zipfile.ZipFile(z) as zf:
        zf.extractall(tmp)
    inner = tmp / "target"
    return (inner if inner.is_dir() else tmp), tmp


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("task")
    ap.add_argument("--asof", help="the fiction's as-of date, ISO; dates after it are flagged")
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args()
    task = Path(a.task)
    if not task.is_dir():
        t = a.task if a.task.startswith("task") else "task" + a.task
        task = REPO / t
    if not task.is_dir():
        sys.exit("no task folder: %s" % task)
    prompt_text = (task / "prompt.md").read_text(errors="ignore") if (task / "prompt.md").exists() else ""
    sub = (task / "submission.md").read_text(errors="ignore") if (task / "submission.md").exists() else ""
    note = (task / "DESIGN_NOTE.md").read_text(errors="ignore") if (task / "DESIGN_NOTE.md").exists() else ""
    target, tmp = load_target(task)

    files = []
    for p in sorted(target.rglob("*")):
        if p.is_file():
            text, extras = extract(p)
            files.append({"path": p, "rel": p.relative_to(target), "ext": p.suffix.lower(), "text": text, "extras": extras})

    rep = Report()
    nums, names, call, _ = submission_answers(sub)
    vocab = design_vocab(note, prompt_text)
    sweep_names(files, rep)
    sweep_vocab(files, rep)
    sweep_answers(files, rep, nums, names, call, prompt_text)
    sweep_design_vocab(files, rep, vocab, prompt_text)
    sweep_announce(files, rep, prompt_text)
    sweep_rank_artifact(files, rep, names)
    sweep_hidden(files, rep)
    sweep_columns(files, rep)
    sweep_dates(files, rep, a.asof, prompt_text)
    sweep_metadata(target, rep)
    sweep_prompt(prompt_text, rep)

    level = rep.level()
    lines = ["# leak check, %s" % task.name, "",
             "**Verdict: %s.** %d files read, %d golden figures and %d candidate names taken from submission.md, %d stump terms taken from the design note." % (level, len(files), len(nums), len(names), len(vocab)),
             "", "LEAK stops the ship. REVIEW is a reader's call and the /leak-check command's solver's-eye pass reads every REVIEW line. INFO is a sweep that ran and found nothing or was skipped.", ""]
    if vocab:
        lines += ["Stump terms swept: " + ", ".join(vocab), ""]
    order = sorted(rep.items.keys(), key=lambda k: int(k.split()[0]))
    for k in order:
        items = rep.items[k]
        counts = Counter(lv for lv, _, _ in items)
        lines.append("## %s (%s)" % (k, ", ".join("%s %d" % (lv, counts[lv]) for lv in ("LEAK", "REVIEW", "INFO") if counts[lv])))
        for lv, f, d in sorted(items, key=lambda x: ("LEAK", "REVIEW", "INFO").index(x[0])):
            lines.append("- **%s** `%s`: %s" % (lv, f, d))
        lines.append("")
    ran = set(order)
    for k in ("1 file names", "2 author vocabulary", "3 answer figures in the pack", "4 design-note vocabulary", "5 announcements", "6 ranking artifacts", "7 hidden content", "8 column names", "9 dates after the setting", "10 container metadata", "11 prompt form"):
        if k not in ran:
            lines.append("## %s (clean)\n" % k)
    out = task / "leak_check_report.md"
    out.write_text("\n".join(lines))
    if not a.quiet:
        print("\n".join(lines))
    print("\nverdict: %s  ->  %s" % (level, out))
    return {"LEAK": 2, "REVIEW": 1, "CLEAN": 0}[level]


if __name__ == "__main__":
    sys.exit(main())
