#!/usr/bin/env python3
"""Audit or repair H1 in a task bundle: producer signatures and build-clock timestamps
inside shipped binary inputs.

    python3 scrub_producer_metadata.py <dir>                       audit, writes nothing
    python3 scrub_producer_metadata.py <dir> --apply \
        --producer "Some Organisation" --stamp 2024-10-31          repair in place

Audit is the default because the right producer name and the right in-fiction date are
properties of the build's own fiction and cannot be guessed. Read the audit, then apply.

The repair never re-saves through the writing library, because that reintroduces the very
signature it removes. OOXML is repacked with the same entry names in the same order, touching
only docProps/, and every other entry's CRC is asserted unchanged. PDF is substituted in place
at equal byte length, spending surplus bytes as whitespace between dictionary tokens rather
than as padding inside a value, and the extracted text is asserted identical page for page.
Any assertion failure restores the original and the file is left as it was.
"""
import argparse, os, re, shutil, sys, zipfile

SIG = ["python-docx", "openpyxl", "Openpyxl", "reportlab", "ReportLab",
       "matplotlib", "Matplotlib", "python-pptx", "LibreOffice"]
OOXML = (".docx", ".xlsx", ".pptx")
IMAGES = (".png", ".jpg", ".jpeg", ".svg")
ISO = re.compile(rb"\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ")
PDFDATE = re.compile(rb"D:\d{14}")
APPNAME = {".docx": "Microsoft Word", ".xlsx": "Microsoft Excel", ".pptx": "Microsoft PowerPoint"}


def read_meta(path):
    ext = os.path.splitext(path)[1].lower()
    if ext in OOXML:
        with zipfile.ZipFile(path) as z:
            return b"".join(z.read(n) for n in z.namelist() if n.startswith("docProps/"))
    if ext == ".pdf" or ext in IMAGES:
        return open(path, "rb").read()
    return None


def audit(path, floor, ceiling):
    blob = read_meta(path)
    if blob is None:
        return None
    txt = blob.decode("utf-8", "ignore")
    names = sorted({w for w in SIG if w in txt})
    dates = set()
    for m in ISO.findall(blob):
        dates.add(m.decode()[:10])
    for m in PDFDATE.findall(blob):
        d = m.decode()[2:10]
        dates.add(f"{d[:4]}-{d[4:6]}-{d[6:8]}")
    # a timestamp contradicts the setting in either direction, so flag both sides of the band
    bad = sorted(d for d in dates if (floor and d < floor) or (ceiling and d > ceiling))
    return names, bad


def parse_pdf_dict(seg):
    """Extract /Key (value) pairs, honouring backslash escapes and nested parentheses, which a
    plain regex cannot do and which ReportLab's own default values require."""
    out, i = {}, 0
    while True:
        m = re.compile(rb"/(\w+)\s*\(").search(seg, i)
        if not m:
            return out
        j, depth = m.end(), 1
        while j < len(seg) and depth:
            c = seg[j:j + 1]
            if c == b"\\":
                j += 2
                continue
            depth += (c == b"(") - (c == b")")
            j += 1
        out[m.group(1)] = seg[m.end():j - 1]
        i = j


def out_of_band(iso_date, floor, ceiling):
    return (floor and iso_date < floor) or (ceiling and iso_date > ceiling)


def scrub_ooxml(path, producer, stamp, floor=None, ceiling=None):
    ext = os.path.splitext(path)[1].lower()
    iso = f"{stamp}T00:00:00Z".encode()
    with zipfile.ZipFile(path) as zin:
        infos = zin.infolist()
        data = {i.filename: zin.read(i.filename) for i in infos}
        crc = {i.filename: i.CRC for i in infos}
    for name in [n for n in data if n.startswith("docProps/")]:
        b = data[name]
        b = re.sub(rb"(<dc:creator[^>]*>)[^<]*(</dc:creator>)",
                   rb"\g<1>" + producer.encode() + rb"\g<2>", b)
        b = re.sub(rb"(<cp:lastModifiedBy[^>]*>)[^<]*(</cp:lastModifiedBy>)",
                   rb"\g<1>" + producer.encode() + rb"\g<2>", b)
        b = re.sub(rb"<dc:description[^>]*>[^<]*generated by [^<]*</dc:description>",
                   b"<dc:description></dc:description>", b)
        b = re.sub(rb"(<Application>)[^<]*(</Application>)",
                   rb"\g<1>" + APPNAME[ext].encode() + rb"\g<2>", b)
        # rewrite only the stamps the audit flagged. Silently moving an in-band date would be
        # a change to a field nothing reported, which is how a repair introduces its own defect.
        b = ISO.sub(lambda m: iso if out_of_band(m.group(0).decode()[:10], floor, ceiling)
                    else m.group(0), b)
        data[name] = b
    tmp = path + ".scrub"
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
        for i in infos:
            zi = zipfile.ZipInfo(i.filename, date_time=i.date_time)
            zi.compress_type, zi.external_attr = i.compress_type, i.external_attr
            zi.internal_attr, zi.create_system = i.internal_attr, i.create_system
            zout.writestr(zi, data[i.filename])
    with zipfile.ZipFile(tmp) as chk:
        assert [i.filename for i in chk.infolist()] == [i.filename for i in infos], "entry set moved"
        for i in chk.infolist():
            if not i.filename.startswith("docProps/"):
                assert i.CRC == crc[i.filename], f"body entry changed: {i.filename}"
        blob = b"".join(chk.read(n) for n in chk.namelist() if n.startswith("docProps/"))
        for tok in SIG:
            assert tok.encode() not in blob, f"{path}: {tok} survived"
    os.replace(tmp, path)


def scrub_pdf(path, producer, stamp, floor=None, ceiling=None):
    b = open(path, "rb").read()
    n0 = len(b)
    date = f"D:{stamp.replace('-', '')}000000".encode()
    m = re.search(rb"/Author[^\n]*?/Producer \([^)]*\)[^\n]*", b)
    if m:
        span = m.end() - m.start()
        seg = b[m.start():m.end()]
        keep = parse_pdf_dict(seg)
        # a naive ")"-terminated scan truncates any value carrying an escaped or nested paren,
        # and the surplus check cannot catch it because a shorter value still fits the slot.
        # ReportLab's own defaults are escaped, so this is the common case rather than the edge.
        for k, v in keep.items():
            assert b"(" + v + b")" in seg, f"{path}: /{k.decode()} did not round-trip"
        tz = re.search(rb"D:\d{14}([+-]\d\d'\d\d')", b[m.start():m.end()])
        # keep the whole stamp when it is kept: matching only the date part and writing that back
        # truncates D:YYYYMMDDHHMMSS to D:YYYYMMDD, which is a malformed PDF date
        cur = re.search(rb"D:(\d{4})(\d\d)(\d\d)(?:\d{6})?", seg)
        cur_iso = "-".join(x.decode() for x in cur.groups()) if cur else None
        keep_date = cur_iso is not None and not out_of_band(cur_iso, floor, ceiling)
        d = (cur.group(0) if keep_date else date) + (tz.group(1) if tz else b"")
        parts = [b"/Author (%s)" % keep.get(b"Author", b""),
                 b"/CreationDate (%s)" % d,
                 b"/Creator (%s)" % keep.get(b"Creator", b""),
                 b"/Keywords (%s)" % keep.get(b"Keywords", b""),
                 b"/ModDate (%s)" % d,
                 b"/Producer (%s)" % producer.encode()]
        base = b" ".join(parts) + b" "
        surplus = span - len(base)
        assert surplus >= 0, f"{path}: producer name too long for the slot by {-surplus} bytes"
        gaps = [1] * (len(parts) - 1)
        for i in range(surplus):
            gaps[i % len(gaps)] += 1
        new = parts[0]
        for g, part in zip(gaps, parts[1:]):
            new += b" " * g + part
        new += b" "
        assert len(new) == span
        b = b[:m.start()] + new + b[m.end():]
    # Remaining hits sit in PDF comments, invisible to a reader, so equal-length padding is safe
    # there. Substitute only the text AFTER the comment marker: swallowing the leading "%" turns
    # the comment into loose tokens and corrupts the file.
    for tok in SIG:
        for line in re.findall(rb"[^\n]*" + tok.encode() + rb"[^\n]*", b):
            mark = re.match(rb"(\s*%+\s*)(.*)", line, re.S)
            if not mark:
                continue
            head, body = mark.group(1), mark.group(2)
            b = b.replace(line, head + producer.encode().ljust(len(body))[:len(body)])
    assert len(b) == n0, f"{path}: byte length moved, xref would be corrupt"
    open(path, "wb").write(b)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("directory")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--producer", help="in-fiction author, required with --apply")
    ap.add_argument("--stamp", help="in-fiction export date YYYY-MM-DD, required with --apply")
    ap.add_argument("--floor", help="earliest plausible date for the setting, YYYY-MM-DD")
    ap.add_argument("--ceiling", help="latest plausible date for the setting, YYYY-MM-DD")
    a = ap.parse_args()
    if a.apply and not (a.producer and a.stamp):
        ap.error("--apply needs --producer and --stamp; neither can be guessed from the pack")
    ceiling = a.ceiling or a.stamp
    findings, repaired = [], []
    for f in sorted(os.listdir(a.directory)):
        p = os.path.join(a.directory, f)
        if not os.path.isfile(p):
            continue
        r = audit(p, a.floor, ceiling)
        if r is None or not (r[0] or r[1]):
            continue
        names, bad = r
        findings.append((f, names, bad))
        if not a.apply:
            continue
        bak = p + ".pre-scrub"
        shutil.copy2(p, bak)
        try:
            fn = scrub_pdf if f.lower().endswith(".pdf") else scrub_ooxml
            fn(p, a.producer, a.stamp, a.floor, ceiling)
            if f.lower().endswith(".pdf"):
                # pypdf degrades on a corrupt xref rather than raising, so comparing extracted
                # text alone passes on a file that no longer parses. Fail on any logged error.
                import io, logging
                from pypdf import PdfReader
                cap = io.StringIO()
                h = logging.StreamHandler(cap)
                logging.getLogger("pypdf").addHandler(h)
                try:
                    before = [x.extract_text() for x in PdfReader(bak).pages]
                    quiet = cap.getvalue()
                    after = [x.extract_text() for x in PdfReader(p).pages]
                    noise = cap.getvalue()[len(quiet):]
                finally:
                    logging.getLogger("pypdf").removeHandler(h)
                assert not noise.strip(), f"{f}: the repaired file no longer parses cleanly"
                assert before == after, f"{f}: extracted text moved"
            shutil.copystat(bak, p)
            os.remove(bak)
            repaired.append(f)
        except Exception as e:
            shutil.move(bak, p)
            print(f"  LEFT AS WAS  {f}: {e}", file=sys.stderr)
    if not findings:
        print(f"{a.directory}: clean, no producer signature and no out-of-band timestamp")
        return 0
    for f, names, bad in findings:
        print(f"  {f:52s} {', '.join(names) or '-':28s} {', '.join(bad)}")
    print(f"\n{len(findings)} file(s) flagged" + (f", {len(repaired)} repaired" if a.apply
          else ". Re-run with --apply --producer NAME --stamp YYYY-MM-DD to repair."))
    return 0 if (a.apply and len(repaired) == len(findings)) else 1


if __name__ == "__main__":
    sys.exit(main())
